#!/usr/bin/env bash
# https://github.com/olivergondza/bash-strict-mode
set -euo pipefail
trap 's=$?; echo >&2 "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

OPENRC_DIR="$(realpath ~/.openrc/files)"

if [ $# -le 1 ]; then
  echo >&2 "Usage: openrc <openrc-file> [<COMMAND>...]"
  exit 1
fi

openrc_file_name="$OPENRC_DIR/$1"
if [ ! -f "$openrc_file_name" ]; then
  echo >&2 "'$1' is not a valid name of openrc file in $OPENRC_DIR ($openrc_file_name does not exist)"
  exit 1
fi
shift

source "$openrc_file_name"
exec "$@"
